### ISSUE TITLE
Publish extension to open-vsx.org

### ISSUE THREAD

**Issue by jduchateau** [jamestiotio/compstruct-vscode#5]
Hello,
Thank you for this extension.

Would it be possible to also publish to [open-vsx.org](https://open-vsx.org)?
This registry is typically used by default in _Code - OSS_ because of [legals reason](https://github.com/microsoft/vscode/wiki/Differences-between-the-repository-and-Visual-Studio-Code). Therefore, for now, we need to download and install the extension manually.
Thanks.

**Comment by jamestiotio** [comment]
Hello there @jduchateau!

Thank you for bringing this up! I was not aware of Open VSX until now. I did some research and now I am aware of what is going on with the various legal licensing issues.

I have made the necessary adjustments to the GitHub actions workflow and I have published `v0.1.1` using the latest commit (b75173945811031af59bc3daf56897c6a763e078) with an updated README to both Microsoft's Visual Studio Code Marketplace and Eclipse's Open VSX Registry. Hope that helps!

Glad that you like this extension.

Cheers!
